import { useState, useCallback, useRef, useEffect } from 'react'
import Map, { Marker, Source, Layer } from 'react-map-gl/mapbox'
import { Scrollama, Step } from 'react-scrollama'
import { motion, AnimatePresence } from 'framer-motion'
import ReactMarkdown from 'react-markdown'
import { ArrowUp, ChevronLeft, ChevronRight, ChevronsLeftRight } from 'lucide-react'
import { CHAPTERS } from './chapters.js'

const MAPBOX_TOKEN = import.meta.env.VITE_MAPBOX_ACCESS_TOKEN

// Alaska Highway return — ferry leg: Auke Bay (Juneau) → Haines via Lynn Canal
// Generated by searoute Python library (maritime routing network, AIS-derived)
const HAINES_FERRY_ROUTE_COORDS = [
  [-134.6456, 58.3847], // Auke Bay AMHS terminal, Juneau
  [-134.7716, 58.3655],
  [-134.8681, 58.4939],
  [-135.0278, 58.5502],
  [-135.1864, 58.8387],
  [-135.2327, 59.0787],
  [-135.3000, 59.1876],
  [-135.3765, 59.2658],
  [-135.4458, 59.2356], // Haines AMHS terminal
]

const HAINES_FERRY_GEOJSON = {
  type: 'Feature',
  geometry: { type: 'LineString', coordinates: HAINES_FERRY_ROUTE_COORDS },
}

// Alaska Highway return — road leg: Haines → Alaska Hwy → Whitehorse → Cassiar Hwy → Seattle
const ALASKA_ROAD_ROUTE_COORDS = [
  [-135.4458, 59.2356], // Haines AMHS terminal
  [-135.89,   59.42  ], // Klukwan
  [-136.50,   59.75  ], // Chilkat Pass
  [-137.35,   60.50  ], // approaching Haines Junction
  [-137.51,   60.76  ], // Haines Junction, YT
  [-136.70,   60.74  ], // east on Alaska Highway
  [-135.06,   60.72  ], // Whitehorse, YT
  [-133.00,   60.35  ], // continuing east
  [-128.71,   60.06  ], // Watson Lake, YT
  [-129.42,   59.68  ], // Cassiar Hwy 37 junction
  [-130.03,   58.43  ], // Dease Lake, BC
  [-130.24,   57.50  ], // Bob Quinn Lake area
  [-129.32,   56.08  ], // Meziadin Junction
  [-128.08,   55.12  ], // Kitwanga — Yellowhead Hwy 16 junction
  [-127.67,   54.78  ], // Smithers
  [-122.75,   53.91  ], // Prince George
  [-121.44,   49.38  ], // Hope, BC
  [-122.30,   49.00  ], // Sumas/Abbotsford border crossing
  [-122.48,   48.74  ], // Bellingham, WA
  [-122.33,   47.61  ], // Seattle
]

const ALASKA_ROAD_GEOJSON = {
  type: 'Feature',
  geometry: { type: 'LineString', coordinates: ALASKA_ROAD_ROUTE_COORDS },
}

// Combined coords for single tracer animation (ferry → road, no duplicate Haines)
const ALASKA_HWY_ALL_COORDS = [
  ...HAINES_FERRY_ROUTE_COORDS,
  ...ALASKA_ROAD_ROUTE_COORDS.slice(1),
]

// Wings Airways seaplane — downtown Juneau to Taku Lodge
const SEAPLANE_ROUTE_COORDS = [
  [-134.419, 58.301], // Wings Airways seaplane base, downtown Juneau
  [-134.30,  58.320], // over Gastineau Channel / icefield edge
  [-134.15,  58.360], // approaching Taku Glacier
  [-134.01,  58.390], // Taku Lodge on the Taku River
]

const SEAPLANE_ROUTE_GEOJSON = {
  type: 'Feature',
  geometry: { type: 'LineString', coordinates: SEAPLANE_ROUTE_COORDS },
}

// Alaska Marine Highway route — Bellingham to Auke Bay (Juneau) via Inside Passage
// Generated by searoute maritime routing network (42 waypoints, ~1541 km, all water)
const FERRY_ROUTE_COORDS = [
  [-122.7291, 48.6586],
  [-122.7764, 48.7537],
  [-123.0510, 48.8551],
  [-123.3795, 49.0699],
  [-124.5711, 49.8731],
  [-125.5688, 50.5508],
  [-127.3618, 50.8984],
  [-128.2191, 51.4191],
  [-129.3882, 52.1684],
  [-130.7582, 53.5950],
  [-130.3302, 54.3000],
  [-130.6320, 54.6350],
  [-131.1618, 54.6716],
  [-131.5619, 54.6384],
  [-131.8201, 55.0516],
  [-131.9715, 55.4041],
  [-132.0329, 55.4630],
  [-132.2249, 55.5793],
  [-132.3634, 55.7782],
  [-132.8098, 56.1430],
  [-132.9462, 56.2723],
  [-133.0771, 56.3252],
  [-133.1599, 56.3524],
  [-133.2207, 56.3950],
  [-133.0574, 56.4464],
  [-132.6948, 56.4848],
  [-132.5313, 56.5764],
  [-132.5311, 56.6120],
  [-132.5687, 56.6183],
  [-132.6269, 56.6821],
  [-133.0346, 57.0141],
  [-133.7921, 57.2025],
  [-133.7230, 57.5816],
  [-133.8181, 57.8253],
  [-134.0668, 58.0508],
  [-134.0790, 58.1000],
  [-134.1473, 58.1713],
  [-134.2079, 58.1841],
  [-134.2487, 58.1773],
  [-134.5728, 58.2038],
  [-134.7658, 58.3179], // north of Douglas Island
  [-134.7716, 58.3655], // Auke Bay approach
  [-134.6456, 58.3847], // AMHS Auke Bay terminal, Juneau
]

const FERRY_ROUTE_GEOJSON = {
  type: 'Feature',
  geometry: { type: 'LineString', coordinates: FERRY_ROUTE_COORDS },
}

// Interpolate a point at progress t (0–1) along a coordinate array
function interpolateAlongLine(coords, t) {
  if (t <= 0) return coords[0]
  if (t >= 1) return coords[coords.length - 1]
  const dists = []
  let total = 0
  for (let i = 1; i < coords.length; i++) {
    const dx = coords[i][0] - coords[i - 1][0]
    const dy = coords[i][1] - coords[i - 1][1]
    dists.push(Math.sqrt(dx * dx + dy * dy))
    total += dists[dists.length - 1]
  }
  let rem = t * total
  for (let i = 0; i < dists.length; i++) {
    if (rem <= dists[i]) {
      const s = rem / dists[i]
      return [
        coords[i][0] + s * (coords[i + 1][0] - coords[i][0]),
        coords[i][1] + s * (coords[i + 1][1] - coords[i][1]),
      ]
    }
    rem -= dists[i]
  }
  return coords[coords.length - 1]
}

const MD_COMPONENTS = {
  a: ({ href, children }) => (
    <a href={href} target="_blank" rel="noopener noreferrer" className="text-blue-600 underline hover:text-blue-800">
      {children}
    </a>
  ),
}

function IntroCard({ chapter }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.5, ease: 'easeOut' }}
      className="bg-white/90 backdrop-blur-md rounded-2xl shadow-xl p-8 border border-white/60 max-w-md w-full"
    >
      <h1 className="text-3xl font-bold mb-4 text-gray-900">
        {chapter.title}
      </h1>
      <div className="text-gray-700 leading-relaxed prose max-w-none">
        <ReactMarkdown components={MD_COMPONENTS}>{chapter.content}</ReactMarkdown>
      </div>
      <p className="mt-5 text-xs text-gray-400 font-medium tracking-wide">Scroll to explore ↓</p>
    </motion.div>
  )
}

function PhotoSlider({ photos }) {
  const [pairIdx, setPairIdx] = useState(0)
  const [pos, setPos] = useState(50)
  const containerRef = useRef(null)
  const dragging = useRef(false)
  const pairCount = photos.length - 1

  const front = photos[pairIdx]
  const back = photos[pairIdx + 1]

  const updatePos = useCallback((clientX) => {
    if (!containerRef.current) return
    const rect = containerRef.current.getBoundingClientRect()
    setPos(Math.max(2, Math.min(98, ((clientX - rect.left) / rect.width) * 100)))
  }, [])

  useEffect(() => {
    const onMove = (e) => { if (dragging.current) updatePos(e.clientX) }
    const onUp = () => { dragging.current = false }
    window.addEventListener('mousemove', onMove)
    window.addEventListener('mouseup', onUp)
    return () => { window.removeEventListener('mousemove', onMove); window.removeEventListener('mouseup', onUp) }
  }, [updatePos])

  useEffect(() => {
    const el = containerRef.current
    if (!el) return
    const onTouchMove = (e) => { if (dragging.current) { e.preventDefault(); updatePos(e.touches[0].clientX) } }
    el.addEventListener('touchmove', onTouchMove, { passive: false })
    return () => el.removeEventListener('touchmove', onTouchMove)
  }, [updatePos])

  const goTo = (i) => { setPairIdx(i); setPos(50) }

  return (
    <div className="mt-4">
      <div
        ref={containerRef}
        className="relative aspect-video rounded-xl overflow-hidden bg-gray-100 select-none cursor-ew-resize"
        onMouseDown={(e) => { dragging.current = true; updatePos(e.clientX) }}
        onTouchStart={(e) => { dragging.current = true; updatePos(e.touches[0].clientX) }}
        onTouchEnd={() => { dragging.current = false }}
      >
        <img src={back.src} alt={back.alt ?? ''} className="absolute inset-0 w-full h-full object-cover pointer-events-none" draggable={false} />
        <img src={front.src} alt={front.alt ?? ''} className="absolute inset-0 w-full h-full object-cover pointer-events-none" draggable={false} style={{ clipPath: `inset(0 ${100 - pos}% 0 0)` }} />
        <div className="absolute top-0 bottom-0 w-px bg-white/90 shadow-[0_0_6px_rgba(0,0,0,0.5)] pointer-events-none z-10" style={{ left: `${pos}%` }}>
          <div className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-9 h-9 bg-white rounded-full shadow-xl flex items-center justify-center">
            <ChevronsLeftRight size={15} strokeWidth={2.5} className="text-gray-600" />
          </div>
        </div>
        {front.alt && <span className="absolute bottom-2 left-2 text-white text-xs font-medium bg-black/50 px-2 py-0.5 rounded pointer-events-none">{front.alt}</span>}
        {back.alt && <span className="absolute bottom-2 right-2 text-white text-xs font-medium bg-black/50 px-2 py-0.5 rounded pointer-events-none text-right">{back.alt}</span>}
      </div>
      {pairCount > 1 && (
        <div className="flex justify-center items-center gap-3 mt-2">
          <button onClick={() => goTo((pairIdx - 1 + pairCount) % pairCount)} className="w-6 h-6 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors" aria-label="Previous comparison">
            <ChevronLeft size={16} strokeWidth={2.5} className="text-gray-500" />
          </button>
          <div className="flex gap-1.5">
            {Array.from({ length: pairCount }).map((_, i) => (
              <button key={i} onClick={() => goTo(i)} className={`w-2 h-2 rounded-full transition-colors ${i === pairIdx ? 'bg-gray-800' : 'bg-gray-300'}`} aria-label={`Comparison ${i + 1}`} />
            ))}
          </div>
          <button onClick={() => goTo((pairIdx + 1) % pairCount)} className="w-6 h-6 flex items-center justify-center rounded-full hover:bg-gray-100 transition-colors" aria-label="Next comparison">
            <ChevronRight size={16} strokeWidth={2.5} className="text-gray-500" />
          </button>
        </div>
      )}
    </div>
  )
}

function ChapterCard({ chapter }) {
  const Icon = chapter.icon
  return (
    <motion.div
      initial={{ opacity: 0, x: -24 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -24 }}
      transition={{ duration: 0.4, ease: 'easeOut' }}
      className="bg-white/90 backdrop-blur-md rounded-2xl shadow-xl p-6 border border-white/60 max-w-sm w-full"
    >
      {Icon && (
        <>
          <div
            className="flex items-center justify-center w-10 h-10 rounded-full mb-3 shadow-sm"
            style={{ backgroundColor: chapter.color ?? '#1e40af' }}
          >
            <Icon size={20} color="white" strokeWidth={2} />
          </div>
          {chapter.subtitle && (
            <p className="text-xs font-semibold uppercase tracking-widest mb-1" style={{ color: chapter.color ?? '#1e40af' }}>
              {chapter.subtitle}
            </p>
          )}
        </>
      )}
      <h2 className="text-xl font-bold text-gray-900 mb-3">{chapter.title}</h2>
      <div className="text-gray-700 text-sm leading-relaxed prose prose-sm max-w-none">
        <ReactMarkdown components={MD_COMPONENTS}>{chapter.content}</ReactMarkdown>
      </div>
      {chapter.photos?.length === 1 && (
        <figure className="mt-4">
          <img src={chapter.photos[0].src} alt={chapter.photos[0].alt ?? ''} className="w-full rounded-xl object-cover" />
          {chapter.photos[0].alt && (
            <figcaption className="mt-1.5 text-xs text-gray-400 text-center">{chapter.photos[0].alt}</figcaption>
          )}
        </figure>
      )}
      {chapter.photos?.length > 1 && <PhotoSlider photos={chapter.photos} />}
    </motion.div>
  )
}

function TabBar({ activeTab, onTabChange, visible }) {
  const tabs = [
    { id: 'map', label: 'Map' },
    { id: 'calendar', label: 'Calendar' },
    { id: 'bookings', label: 'Bookings' },
  ]
  return (
    <div className={`fixed top-4 left-1/2 -translate-x-1/2 z-50 flex bg-white/90 backdrop-blur-md rounded-full shadow-xl border border-white/60 p-1 transition-opacity duration-300 ${visible ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}>
      {tabs.map(tab => (
        <button
          key={tab.id}
          onClick={() => onTabChange(tab.id)}
          className={`px-5 py-2 rounded-full text-sm font-semibold transition-all ${
            activeTab === tab.id
              ? 'bg-gray-900 text-white shadow-sm'
              : 'text-gray-600 hover:text-gray-900'
          }`}
        >
          {tab.label}
        </button>
      ))}
    </div>
  )
}

function CalendarTab() {
  return (
    <div className="fixed inset-0 z-20 flex items-center justify-center pt-16 px-6">
      <div className="bg-white/90 backdrop-blur-md rounded-2xl shadow-xl p-8 border border-white/60 max-w-lg w-full">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Calendar</h2>
        <p className="text-gray-400 text-sm">Trip dates and itinerary coming soon.</p>
      </div>
    </div>
  )
}

function BookingsTab() {
  return (
    <div className="fixed inset-0 z-20 flex items-center justify-center pt-16 px-6">
      <div className="bg-white/90 backdrop-blur-md rounded-2xl shadow-xl p-8 border border-white/60 max-w-lg w-full">
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Bookings</h2>
        <p className="text-gray-400 text-sm">Reservations and booking links coming soon.</p>
      </div>
    </div>
  )
}

function ReturnToStartButton({ visible, onReturn }) {
  return (
    <AnimatePresence>
      {visible && (
        <motion.button
          key="return-to-start"
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 24 }}
          transition={{ duration: 0.4, ease: 'easeOut' }}
          onClick={onReturn}
          className="fixed bottom-6 left-1/2 -translate-x-1/2 z-40 flex items-center gap-2 px-5 py-3 rounded-full shadow-xl font-semibold text-sm text-white tracking-wide bg-gray-900"
          aria-label="Return to start"
        >
          <ArrowUp size={16} strokeWidth={2.5} />
          Return to start
        </motion.button>
      )}
    </AnimatePresence>
  )
}

const LAST_CHAPTER_ID = CHAPTERS[CHAPTERS.length - 1].id
const FIRST_CHAPTER_ID = CHAPTERS[0].id

export default function App() {
  const [activeTab, setActiveTab] = useState('map')
  const [activeChapterId, setActiveChapterId] = useState(CHAPTERS[0].id)
  const [showReturnButton, setShowReturnButton] = useState(false)
  const mapRef = useRef(null)
  const isReturningRef = useRef(false)
  const tracerAnimRef = useRef(null)
  const seaplaneAnimRef = useRef(null)
  const roadAnimRef = useRef(null)
  const [tabsVisible, setTabsVisible] = useState(true)

  useEffect(() => {
    const onScroll = () => setTabsVisible(window.scrollY < 50)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  // Deep link: scroll to chapter on load if hash present
  useEffect(() => {
    const hash = window.location.hash.slice(1)
    if (!hash) return
    setTimeout(() => {
      const el = document.getElementById(hash)
      if (el) el.scrollIntoView({ behavior: 'instant' })
    }, 100)
  }, [])

  // Tron tracer animation for the ferry chapter
  useEffect(() => {
    if (activeChapterId !== 'ferry') {
      if (tracerAnimRef.current) {
        cancelAnimationFrame(tracerAnimRef.current)
        tracerAnimRef.current = null
      }
      return
    }

    // Each pass: 6000ms travel + 800ms pause before looping
    const TRAVEL = 6000
    const PAUSE = 800
    const CYCLE = TRAVEL + PAUSE
    const startTime = performance.now()

    const animate = (now) => {
      const elapsed = (now - startTime) % CYCLE
      const raw = Math.min(elapsed / TRAVEL, 1)
      // ease-in-out quad
      const t = raw < 0.5 ? 2 * raw * raw : -1 + (4 - 2 * raw) * raw
      const coord = interpolateAlongLine(FERRY_ROUTE_COORDS, t)

      const map = mapRef.current?.getMap()
      const src = map?.getSource('ferry-point')
      if (src) {
        src.setData({ type: 'Feature', geometry: { type: 'Point', coordinates: coord } })
      }

      tracerAnimRef.current = requestAnimationFrame(animate)
    }

    tracerAnimRef.current = requestAnimationFrame(animate)
    return () => {
      if (tracerAnimRef.current) cancelAnimationFrame(tracerAnimRef.current)
    }
  }, [activeChapterId])

  // Tron tracer animation for the seaplane chapter
  useEffect(() => {
    if (activeChapterId !== 'taku-feast') {
      if (seaplaneAnimRef.current) {
        cancelAnimationFrame(seaplaneAnimRef.current)
        seaplaneAnimRef.current = null
      }
      return
    }

    // Short 30-mile hop: 3500ms travel + 600ms pause per loop
    const TRAVEL = 3500
    const PAUSE = 600
    const CYCLE = TRAVEL + PAUSE
    const startTime = performance.now()

    const animate = (now) => {
      const elapsed = (now - startTime) % CYCLE
      const raw = Math.min(elapsed / TRAVEL, 1)
      const t = raw < 0.5 ? 2 * raw * raw : -1 + (4 - 2 * raw) * raw
      const coord = interpolateAlongLine(SEAPLANE_ROUTE_COORDS, t)

      const map = mapRef.current?.getMap()
      const src = map?.getSource('seaplane-point')
      if (src) {
        src.setData({ type: 'Feature', geometry: { type: 'Point', coordinates: coord } })
      }

      seaplaneAnimRef.current = requestAnimationFrame(animate)
    }

    seaplaneAnimRef.current = requestAnimationFrame(animate)
    return () => {
      if (seaplaneAnimRef.current) cancelAnimationFrame(seaplaneAnimRef.current)
    }
  }, [activeChapterId])

  // Tron tracer animation for the Alaska Highway road chapter
  useEffect(() => {
    if (activeChapterId !== 'alaska-highway') {
      if (roadAnimRef.current) {
        cancelAnimationFrame(roadAnimRef.current)
        roadAnimRef.current = null
      }
      return
    }

    // Long 1800-mile drive: 14000ms travel + 1000ms pause per loop
    const TRAVEL = 14000
    const PAUSE = 1000
    const CYCLE = TRAVEL + PAUSE
    const startTime = performance.now()

    const animate = (now) => {
      const elapsed = (now - startTime) % CYCLE
      const raw = Math.min(elapsed / TRAVEL, 1)
      const t = raw < 0.5 ? 2 * raw * raw : -1 + (4 - 2 * raw) * raw
      const coord = interpolateAlongLine(ALASKA_HWY_ALL_COORDS, t)

      const map = mapRef.current?.getMap()
      const src = map?.getSource('road-point')
      if (src) {
        src.setData({ type: 'Feature', geometry: { type: 'Point', coordinates: coord } })
      }

      roadAnimRef.current = requestAnimationFrame(animate)
    }

    roadAnimRef.current = requestAnimationFrame(animate)
    return () => {
      if (roadAnimRef.current) cancelAnimationFrame(roadAnimRef.current)
    }
  }, [activeChapterId])

  const handleStepEnter = useCallback(({ data }) => {
    if (isReturningRef.current) {
      if (data === FIRST_CHAPTER_ID) {
        isReturningRef.current = false
        setActiveChapterId(FIRST_CHAPTER_ID)
        history.replaceState(null, '', `#${FIRST_CHAPTER_ID}`)
      }
      return
    }
    const chapter = CHAPTERS.find(c => c.id === data)
    if (!chapter) return
    setActiveChapterId(chapter.id)
    history.replaceState(null, '', `#${chapter.id}`)
    if (chapter.id === LAST_CHAPTER_ID) {
      setShowReturnButton(false)
    }
    if (mapRef.current) {
      const states = chapter.mapStates
      if (states?.length >= 2) {
        const flyNext = (idx) => {
          if (idx >= states.length) return
          const s = states[idx]
          mapRef.current?.flyTo({
            center: [s.longitude, s.latitude],
            zoom: s.zoom,
            pitch: s.pitch ?? 0,
            bearing: s.bearing ?? 0,
            duration: idx === 0 ? 800 : 3000,
            essential: true,
          })
          if (idx < states.length - 1) {
            mapRef.current?.getMap().once('moveend', () => flyNext(idx + 1))
          }
        }
        flyNext(0)
      } else if (chapter.mapState) {
        mapRef.current.flyTo({
          center: [chapter.mapState.longitude, chapter.mapState.latitude],
          zoom: chapter.mapState.zoom,
          pitch: chapter.mapState.pitch ?? 0,
          bearing: chapter.mapState.bearing ?? 0,
          duration: 1800,
          essential: true,
        })
      }
    }
  }, [])

  const handleStepExit = useCallback(({ data, direction }) => {
    if (data === LAST_CHAPTER_ID && direction === 'down') {
      setShowReturnButton(true)
    }
    if (data === LAST_CHAPTER_ID && direction === 'up') {
      setShowReturnButton(false)
    }
  }, [])

  const handleReturn = useCallback(() => {
    isReturningRef.current = true
    setShowReturnButton(false)
    window.scrollTo({ top: 0, behavior: 'smooth' })
    const first = CHAPTERS[0]
    if (mapRef.current && first.mapState) {
      mapRef.current.flyTo({
        center: [first.mapState.longitude, first.mapState.latitude],
        zoom: first.mapState.zoom,
        pitch: first.mapState.pitch ?? 0,
        bearing: first.mapState.bearing ?? 0,
        duration: 1800,
        essential: true,
      })
    }
  }, [])

  const activeChapter = CHAPTERS.find(c => c.id === activeChapterId) ?? CHAPTERS[0]

  return (
    <div className="relative">
      <TabBar activeTab={activeTab} onTabChange={setActiveTab} visible={activeTab !== 'map' || tabsVisible} />

      {activeTab === 'calendar' && <CalendarTab />}
      {activeTab === 'bookings' && <BookingsTab />}

      {/* Fixed full-screen map */}
      <div className="fixed inset-0 z-0">
        <Map
          ref={mapRef}
          mapboxAccessToken={MAPBOX_TOKEN}
          initialViewState={CHAPTERS[0].mapState}
          mapStyle="mapbox://styles/mapbox/outdoors-v12"
          style={{ width: '100%', height: '100%' }}
        >
          {activeChapterId === 'ferry' && (
            <>
              {/* Tron glow track */}
              <Source id="ferry-route" type="geojson" data={FERRY_ROUTE_GEOJSON}>
                <Layer
                  id="ferry-glow-outer"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 28, 'line-color': '#00e5ff', 'line-opacity': 0.07, 'line-blur': 14 }}
                />
                <Layer
                  id="ferry-glow-mid"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 12, 'line-color': '#00e5ff', 'line-opacity': 0.2, 'line-blur': 5 }}
                />
                <Layer
                  id="ferry-glow-inner"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 5, 'line-color': '#00bcd4', 'line-opacity': 0.65 }}
                />
                <Layer
                  id="ferry-core"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 1.5, 'line-color': '#e0ffff', 'line-opacity': 0.95 }}
                />
              </Source>
              {/* Moving point — updated imperatively each frame */}
              <Source
                id="ferry-point"
                type="geojson"
                data={{ type: 'Feature', geometry: { type: 'Point', coordinates: FERRY_ROUTE_COORDS[0] } }}
              >
                <Layer
                  id="ferry-pt-halo-3"
                  type="circle"
                  paint={{ 'circle-radius': 28, 'circle-color': '#00e5ff', 'circle-opacity': 0.07, 'circle-blur': 1 }}
                />
                <Layer
                  id="ferry-pt-halo-2"
                  type="circle"
                  paint={{ 'circle-radius': 14, 'circle-color': '#00bcd4', 'circle-opacity': 0.25 }}
                />
                <Layer
                  id="ferry-pt-halo-1"
                  type="circle"
                  paint={{ 'circle-radius': 8, 'circle-color': '#00e5ff', 'circle-opacity': 0.55 }}
                />
                <Layer
                  id="ferry-pt-core"
                  type="circle"
                  paint={{
                    'circle-radius': 5,
                    'circle-color': '#ffffff',
                    'circle-opacity': 1,
                    'circle-stroke-width': 2.5,
                    'circle-stroke-color': '#00e5ff',
                  }}
                />
              </Source>
            </>
          )}

          {activeChapterId === 'taku-feast' && (
            <>
              {/* Seaplane Tron glow track — amber/gold */}
              <Source id="seaplane-route" type="geojson" data={SEAPLANE_ROUTE_GEOJSON}>
                <Layer
                  id="seaplane-glow-outer"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 28, 'line-color': '#f59e0b', 'line-opacity': 0.07, 'line-blur': 14 }}
                />
                <Layer
                  id="seaplane-glow-mid"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 12, 'line-color': '#f59e0b', 'line-opacity': 0.2, 'line-blur': 5 }}
                />
                <Layer
                  id="seaplane-glow-inner"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 5, 'line-color': '#fbbf24', 'line-opacity': 0.65 }}
                />
                <Layer
                  id="seaplane-core"
                  type="line"
                  layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 1.5, 'line-color': '#fef3c7', 'line-opacity': 0.95 }}
                />
              </Source>
              {/* Moving seaplane point */}
              <Source
                id="seaplane-point"
                type="geojson"
                data={{ type: 'Feature', geometry: { type: 'Point', coordinates: SEAPLANE_ROUTE_COORDS[0] } }}
              >
                <Layer
                  id="seaplane-pt-halo-3"
                  type="circle"
                  paint={{ 'circle-radius': 28, 'circle-color': '#f59e0b', 'circle-opacity': 0.07, 'circle-blur': 1 }}
                />
                <Layer
                  id="seaplane-pt-halo-2"
                  type="circle"
                  paint={{ 'circle-radius': 14, 'circle-color': '#fbbf24', 'circle-opacity': 0.25 }}
                />
                <Layer
                  id="seaplane-pt-halo-1"
                  type="circle"
                  paint={{ 'circle-radius': 8, 'circle-color': '#f59e0b', 'circle-opacity': 0.55 }}
                />
                <Layer
                  id="seaplane-pt-core"
                  type="circle"
                  paint={{
                    'circle-radius': 5,
                    'circle-color': '#ffffff',
                    'circle-opacity': 1,
                    'circle-stroke-width': 2.5,
                    'circle-stroke-color': '#f59e0b',
                  }}
                />
              </Source>
            </>
          )}

          {activeChapterId === 'alaska-highway' && (
            <>
              {/* Ferry leg — cyan, matching the Bellingham ferry style */}
              <Source id="haines-ferry-route" type="geojson" data={HAINES_FERRY_GEOJSON}>
                <Layer id="haines-ferry-glow-outer" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 28, 'line-color': '#00e5ff', 'line-opacity': 0.07, 'line-blur': 14 }} />
                <Layer id="haines-ferry-glow-mid" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 12, 'line-color': '#00e5ff', 'line-opacity': 0.2, 'line-blur': 5 }} />
                <Layer id="haines-ferry-glow-inner" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 5, 'line-color': '#00bcd4', 'line-opacity': 0.65 }} />
                <Layer id="haines-ferry-core" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 1.5, 'line-color': '#e0ffff', 'line-opacity': 0.95 }} />
              </Source>
              {/* Road leg — orange */}
              <Source id="alaska-road-route" type="geojson" data={ALASKA_ROAD_GEOJSON}>
                <Layer id="road-glow-outer" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 28, 'line-color': '#f97316', 'line-opacity': 0.07, 'line-blur': 14 }} />
                <Layer id="road-glow-mid" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 12, 'line-color': '#f97316', 'line-opacity': 0.2, 'line-blur': 5 }} />
                <Layer id="road-glow-inner" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 5, 'line-color': '#fb923c', 'line-opacity': 0.65 }} />
                <Layer id="road-core" type="line" layout={{ 'line-cap': 'round', 'line-join': 'round' }}
                  paint={{ 'line-width': 1.5, 'line-color': '#fff7ed', 'line-opacity': 0.95 }} />
              </Source>
              {/* Single tracer moving through ferry then road */}
              <Source
                id="road-point"
                type="geojson"
                data={{ type: 'Feature', geometry: { type: 'Point', coordinates: HAINES_FERRY_ROUTE_COORDS[0] } }}
              >
                <Layer
                  id="road-pt-halo-3"
                  type="circle"
                  paint={{ 'circle-radius': 28, 'circle-color': '#f97316', 'circle-opacity': 0.07, 'circle-blur': 1 }}
                />
                <Layer
                  id="road-pt-halo-2"
                  type="circle"
                  paint={{ 'circle-radius': 14, 'circle-color': '#fb923c', 'circle-opacity': 0.25 }}
                />
                <Layer
                  id="road-pt-halo-1"
                  type="circle"
                  paint={{ 'circle-radius': 8, 'circle-color': '#f97316', 'circle-opacity': 0.55 }}
                />
                <Layer
                  id="road-pt-core"
                  type="circle"
                  paint={{
                    'circle-radius': 5,
                    'circle-color': '#ffffff',
                    'circle-opacity': 1,
                    'circle-stroke-width': 2.5,
                    'circle-stroke-color': '#f97316',
                  }}
                />
              </Source>
            </>
          )}

          {CHAPTERS.filter(c => c.marker).map(chapter => {
            const Icon = chapter.icon
            const isActive = activeChapterId === chapter.id
            return (
              <Marker
                key={chapter.id}
                longitude={chapter.marker.longitude}
                latitude={chapter.marker.latitude}
                anchor="center"
              >
                <div
                  className="flex items-center justify-center w-9 h-9 rounded-full shadow-lg"
                  style={{
                    backgroundColor: chapter.markerEmoji ? 'rgba(255,255,255,0.92)' : (chapter.color ?? '#1e40af'),
                    transform: isActive ? 'scale(1.3)' : 'scale(1)',
                    transition: 'transform 0.3s ease',
                  }}
                >
                  {chapter.markerEmoji
                    ? <span style={{ fontSize: 20, lineHeight: 1 }}>{chapter.markerEmoji}</span>
                    : Icon && <Icon size={17} color="white" strokeWidth={2.5} />
                  }
                </div>
              </Marker>
            )
          })}
        </Map>
      </div>

      {activeTab === 'map' && (
        <>
          <ReturnToStartButton visible={showReturnButton} onReturn={handleReturn} />

          {/* Scrollytelling story track */}
          <div className="relative z-30">
            <div className="h-20" /> {/* clearance for tab bar */}
            <Scrollama onStepEnter={handleStepEnter} onStepExit={handleStepExit} offset={0.5}>
              {CHAPTERS.map((chapter) => (
                <Step data={chapter.id} key={chapter.id}>
                  <section id={chapter.id} className="min-h-screen flex items-center py-16 px-6 md:px-12">
                    <AnimatePresence>
                      {activeChapter.id === chapter.id &&
                        (chapter.type === 'intro' ? (
                          <IntroCard key={chapter.id} chapter={chapter} />
                        ) : (
                          <ChapterCard key={chapter.id} chapter={chapter} />
                        ))}
                    </AnimatePresence>
                  </section>
                </Step>
              ))}
            </Scrollama>
            <div className="min-h-screen" />
          </div>
        </>
      )}
    </div>
  )
}
